---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_equals
  value: una_notebook.esta_descargado()
name: Prueba sorpresa
