---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe definir el método `es_un_peligro`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe definir el método `__init__`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe definir el método `sabe_correr`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe definir el método `recibir_danio`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Zombi` debe definir el método `regenerarse`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe definir el método `es_un_peligro`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe definir el método `__init__`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe definir el método `recibir_danio`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe definir el método `sabe_correr`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`SuperZombi` debe definir el método `regenerarse`"
  checked: true
name: El regreso de los zombis
