---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`__init__`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`utilizar`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`cargar_a_tope`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`tiene_bateria_maxima`"
  checked: true
name: No repitan conmigo
