---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`Dispositivo` es una clase concreta."
  checked: false
- value: "`Dispositivo` es una clase abstracta."
  checked: true
- value: "`Tablet` es una clase concreta."
  checked: true
- value: "`Tablet` es una clase abstracta."
  checked: false
- value: "`Notebook` es una clase concreta."
  checked: true
- value: "`Notebook` es una clase abstracta."
  checked: false
- value: "`Tablet` hereda de `Dispositivo`."
  checked: true
- value: "`Dispositivo` hereda de `Tablet`."
  checked: false
- value: "`Notebook` hereda de `Dispositivo`."
  checked: true
- value: "`Dispositivo` hereda de `Notebook`."
  checked: false
- value: Las clases abstractas proveen comportamiento a sus subclases.
  checked: true
- value: Las clases abstractas se utilizan para crear instancias.
  checked: false
- value: Las clases concretas proveen comportamiento a su superclase.
  checked: false
- value: Las clases concretas se utilizan para crear instancias.
  checked: true
name: Arte abstracto
